/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      container: {
        center: true,
        screens: {
          xl: "1340px",
          "2xl": "1340px",
        },
        padding: {
          DEFAULT: "1.5rem",
        },
      },
      fontFamily: {
        sans: ["var(--font-inter)", "sans-serif"],
        serif: ["var(--font-merriweather)", "serif"],
      },
      screens: {
        "2hxl": "1400px",
      },
      typography: (theme) => ({
        DEFAULT: {
          css: {
            maxWidth: "100ch",
            h1: {
              fontFamily: ["'Inter'", "sans-serif"],
              fontSize: "36px",
              lineHeight: "120%",
              fontWeight: 800,
            },
            h2: {
              fontFamily: ["'Inter'", "sans-serif"],
              fontSize: "30px",
              lineHeight: "120%",
              marginTop: 0,
              marginBottom: 0,
              fontWeight: 800,
            },
            h3: {
              fontFamily: ["'Inter'", "sans-serif"],
              fontSize: "28px",
              lineHeight: "120%",
              fontWeight: 800,
            },
            h4: {
              fontFamily: ["'Inter'", "sans-serif"],
              fontSize: "24px",
              lineHeight: "130%",
              fontWeight: 800,
            },
            h5: {
              fontFamily: ["'Inter'", "sans-serif"],
              fontSize: "20px",
              lineHeight: "140%",
              fontWeight: 800,
            },
            h6: {
              fontFamily: ["'Inter'", "sans-serif"],
              fontSize: "18px",
              lineHeight: "140%",
              fontWeight: 800,
            },
            p: {
              fontFamily: ["'Merriweather'", "serif"],
              fontSize: "16px",
              lineHeight: "150%",
              color: "#000000",
              fontWeight: 400,
              marginTop: 0,
              marginBottom: 0,
            },
            a: {
              fontFamily: ["'Merriweather'", "serif"],
              fontSize: "14px",
              lineHeight: "150%",
              color: "#000000",
              fontWeight: 500,
              marginTop: 0,
              marginBottom: 0,
            },
            ul: { margin: "0", padding: "0", listStyle: "none" },
            ol: { margin: "0", padding: "0", listStyle: "none" },
            li: { margin: "0", padding: "0" },
          },
        },
        tablet: {
          css: {
            maxWidth: "100ch",
            h1: {
              fontFamily: ["'Inter'", "sans-serif"],
              fontSize: "56px",
              lineHeight: "120%",
              fontWeight: 800,
            },
            h2: {
              fontFamily: ["'Inter'", "sans-serif"],
              fontSize: "40px",
              lineHeight: "120%",
              marginTop: 0,
              marginBottom: 0,
              fontWeight: 800,
            },
            h3: {
              fontFamily: ["'Inter'", "sans-serif"],
              fontSize: "36px",
              lineHeight: "120%",
              fontWeight: 800,
            },
            h4: {
              fontFamily: ["'Inter'", "sans-serif"],
              fontSize: "32px",
              lineHeight: "130%",
              fontWeight: 800,
            },
            h5: {
              fontFamily: ["'Inter'", "sans-serif"],
              fontSize: "24px",
              lineHeight: "140%",
              fontWeight: 800,
            },
            h6: {
              fontFamily: ["'Inter'", "sans-serif"],
              fontSize: "20px",
              lineHeight: "140%",
              fontWeight: 800,
            },
            p: {
              fontFamily: ["'Merriweather'", "serif"],
              fontSize: "16px",
              lineHeight: "150%",
              color: "#000000",
              fontWeight: 400,
              marginTop: 0,
              marginBottom: 0,
            },
            a: {
              fontFamily: ["'Merriweather'", "serif"],
              fontSize: "14px",
              lineHeight: "150%",
              color: "#000000",
              fontWeight: 500,
              marginTop: 0,
              marginBottom: 0,
            },
            ul: { margin: "0", padding: "0", listStyle: "none" },
            ol: { margin: "0", padding: "0", listStyle: "none" },
            li: { margin: "0", padding: "0" },
          },
        },
        desktop: {
          css: {
            maxWidth: "150ch",
            h1: {
              fontFamily: ["'Inter'", "sans-serif"],
              fontSize: "60px",
              lineHeight: "120%",
              fontWeight: 800,
              marginTop: 0,
              marginBottom: 0,
              fontWeight: 800,
            },
            h2: {
              fontFamily: ["'Inter'", "sans-serif"],
              fontSize: "44px",
              lineHeight: "120%",
              marginTop: 0,
              marginBottom: 0,
              fontWeight: 800,
            },
            h3: {
              fontFamily: ["'Inter'", "sans-serif"],
              fontSize: "34px",
              lineHeight: "120%",
              fontWeight: 800,
              marginTop: 0,
              marginBottom: 0,
            },
            h4: {
              fontFamily: ["'Inter'", "sans-serif"],
              fontSize: "28px",
              marginTop: 0,
              fontWeight: 500,
              marginBottom: 0,
              lineHeight: 1,
            },
            h5: {
              fontFamily: ["'Inter'", "sans-serif"],
              fontSize: "24px",
              lineHeight: "140%",
              marginTop: 0,
              marginBottom: 0,
            },
            h6: {
              fontFamily: ["'Inter'", "sans-serif"],
              fontSize: "20px",
              lineHeight: "140%",
              fontWeight: 700,
              marginTop: 0,
              marginBottom: 0,
            },
            p: {
              fontFamily: ["'Merriweather'", "serif"],
              fontSize: "16px",
              lineHeight: "150%",
              color: "#000000",
              fontWeight: 500,
              marginTop: 0,
              marginBottom: 0,
            },
          },
          a: {
            fontFamily: ["'Merriweather'", "serif"],
            fontSize: "14px",
            lineHeight: "150%",
            color: "#000000",
            fontWeight: 500,
            marginTop: 0,
            marginBottom: 0,
          },
          ul: { margin: "0", padding: "0", listStyle: "none" },
          li: { margin: "0", padding: "0" },

          ol: { margin: "0", padding: "0", listStyle: "none" },
        },
      }),
    },
  },
  corePlugins: {
    preflight: false,
  },
};
